name: Accessibility Scanner
on: push # This configures the workflow to run automatically in every PR. Check out https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#on for more options.

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-scanner@v2
        with:
          urls: | # Provide a newline-delimited list of URLs to scan; more information below.
            https://chaoss.community/
            https://chaoss.community/about-chaoss/
            https://chaoss.community/charter/
            https://chaoss.community/code-of-conduct/
            https://chaoss.community/procedure-for-making-a-code-of-conduct-report/
            https://chaoss.community/code-of-conduct-incident-response-plan/
            https://chaoss.community/data-policies/
            https://chaoss.community/governance/
            https://chaoss.community/governing-board/
            https://chaoss.community/chaoss-calendar/
            https://chaoss.community/kb-chaoss-community/
            https://chaoss.community/kb-getting-started/
            https://chaoss.community/chaoss-education/
            https://chaoss.community/kb/working-groups/
            https://chaoss.community/blog/
            https://chaoss.community/chaoss-calendar-talks/
            https://chaoss.community/kb-metrics-and-metrics-models/
            https://chaoss.community/software/
            https://chaoss.community/about-chaoss-practitioner-guides/
          repository: https://github.com/chaoss/website # Provide a repository name-with-owner (in the format "primer/primer-docs"). This is where issues will be filed and where Copilot will open PRs; more information below.
          token: ${{ secrets.GH_TOKEN }} # This token must have write access to the repo above (contents, issues, and PRs); more information below. Note: GitHub Actions' GITHUB_TOKEN cannot be used here.
          cache_key: chaoss-website-scan # Provide a filename that will be used when caching results. We recommend including the name or domain of the site being scanned.
          # login_url: # Optional: URL of the login page if authentication is required
          # username: # Optional: Username for authentication
          # password: ${{ secrets.PASSWORD }} # Optional: Password for authentication (use secrets!)
          # auth_context: # Optional: Stringified JSON object for complex authentication
          # skip_copilot_assignment: false # Optional: Set to true to skip assigning issues to GitHub Copilot (or if you don't have GitHub Copilot)
